{{- if .Values.istio.enabled }}
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: {{ include "amdox.fullname" . }}-api
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  labels:
    {{- include "amdox.labels" . | nindent 4 }}
spec:
  host: {{ include "amdox.componentName" (dict "root" . "component" "api") }}
  subsets:
    - name: stable
      labels:
        rollout.istio.io/revision: stable
    - name: canary
      labels:
        rollout.istio.io/revision: canary
{{- end }}

