apiVersion: v1
kind: Service
metadata:
  name: {{ include "amdox.componentName" (dict "root" . "component" "ml-service") }}
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  labels:
    {{- include "amdox.labels" . | nindent 4 }}
    app.kubernetes.io/component: ml-service
spec:
  selector:
    {{- include "amdox.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: ml-service
  ports:
    - name: http
      port: {{ .Values.mlService.service.port }}
      targetPort: http
