{{- if .Values.secretPlaceholders.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.global.secretName }}
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  labels:
    {{- include "amdox.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $key, $value := .Values.secretPlaceholders.data }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
