apiVersion: v1
kind: Service
metadata:
  name: {{ include "amdox.componentName" (dict "root" . "component" "web") }}
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  labels:
    {{- include "amdox.labels" . | nindent 4 }}
    app.kubernetes.io/component: web
spec:
  selector:
    {{- include "amdox.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: web
  ports:
    - name: http
      port: {{ .Values.web.service.port }}
      targetPort: http
